project:  
  type: website

website:
  title: "Broderick Bownds"
  navbar:
    left:
      - href: resources.qmd
        text: Resources
      - text: E155 Labs
        menu:
          - href: Lab_1.qmd
            text: Lab 1
          - href: Lab_2.qmd
            text: Lab 2
          - href: Lab_3.qmd
            text: Lab 3
          - href: Lab_4.qmd
            text: Lab 4
          - href: Lab_5.qmd
            text: Lab 5
          - href: Lab_6.qmd
            text: Lab 6
          - href: Lab_7.qmd
            text: Lab 7
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



