project:  
  type: website

website:
  title: "Broderick Bownds"
  navbar:
    left:
      - href: resources.qmd
        text: Resources
      - text: E155 Labs
        menu:
          - href: lab 1/Lab_1.qmd
            text: Lab 1
          - href: lab 2/Lab_2.qmd
            text: Lab 2
          - href: lab 3/Lab_3.qmd
            text: Lab 3
          - href: lab 4/Lab_4.qmd
            text: Lab 4
          - href: lab 5/Lab_5.qmd
            text: Lab 5
          - href: lab 6/Lab_6.qmd
            text: Lab 6
          - href: lab 7/Lab_7.qmd
            text: Lab 7
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



